name: Deploy QDOJ with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-qdoj:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip curl git
        curl -fsSL https://get.docker.com | sh
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Clone QDOJ repository
      run: |
        git clone -b 2.0 https://github.com/QingdaoU/OnlineJudgeDeploy.git onlinejudge
        cd onlinejudge

    - name: Start QDOJ services with Docker Compose
      working-directory: ./onlinejudge
      run: |
        sudo docker-compose up -d
        echo "Waiting for containers to start..."
        sleep 60  # Wait for containers to fully initialize
        sudo docker ps -a

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install -y ngrok

    - name: Configure and Start ngrok
      run: |
        ngrok config add-authtoken 2nyiyWrhpT6OwyUoaoZ2zdE9nNo_7KtHBQxaox3Wx2t9qBHTT
        nohup ngrok http 80 > ngrok.log &
        sleep 10  # Give ngrok some time to start

    - name: Display ngrok Public URL
      run: |
        NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r ".tunnels[0].public_url")
        echo "Your ngrok public URL is: $NGROK_URL"

    - name: Keep the workflow alive
      run: |
        echo "Keeping the workflow alive..."
        tail -f /dev/null  # Keep the job running forever
